@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 31 10:19:12 -0400 2022
REM SW Build 2489853 on Tue Mar 26 04:20:25 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim SCI_RX_TX_SHELL_tb_behav -key {Behavioral:rx_tx_shell_sim:Functional:SCI_RX_TX_SHELL_tb} -tclbatch SCI_RX_TX_SHELL_tb.tcl -view C:/Users/mubar/Documents/ENGS31/es31-wordle/vivado_projects/rx_tx_comm/SCI_RX_TX_SHELL_tb_behav_RXTX_ASCII_A_9600Baud.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
