webtalk_init -webtalk_dir O:/ES31/es31-wordle/vivado_projects/master_project/master_project.sim/top_level_sim/behav/xsim/xsim.dir/top_level_shell_tb_full_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun  7 12:57:53 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210643936_1777485687_210738486_023" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "daf371d8-0c19-43e0-a17a-ae9ac3852d83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e178fdf42fb24886994bd89583259cbc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "35" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "4959 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "774 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2338" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "396" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "24.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "963336_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1339023783 -regid "210643936_1777485687_210738486_023" -xml O:/ES31/es31-wordle/vivado_projects/master_project/master_project.sim/top_level_sim/behav/xsim/xsim.dir/top_level_shell_tb_full_behav/webtalk/usage_statistics_ext_xsim.xml -html O:/ES31/es31-wordle/vivado_projects/master_project/master_project.sim/top_level_sim/behav/xsim/xsim.dir/top_level_shell_tb_full_behav/webtalk/usage_statistics_ext_xsim.html -wdm O:/ES31/es31-wordle/vivado_projects/master_project/master_project.sim/top_level_sim/behav/xsim/xsim.dir/top_level_shell_tb_full_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
