webtalk_init -webtalk_dir O:/ES31_22S/es31-worldle/vivado_projects/rx_tx_comm/rx_tx_comm.sim/rx_sim/behav/xsim/xsim.dir/SCI_RECEIVER_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 29 21:37:23 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210643936_1777485687_210738486_023" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f84f1677-91d1-4821-8252-0791d17c8e29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e5ad7dc2426b4cbb945be35845fa2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15012_KB" -context "xsim\\usage"
webtalk_transmit -clientid 551464364 -regid "210643936_1777485687_210738486_023" -xml O:/ES31_22S/es31-worldle/vivado_projects/rx_tx_comm/rx_tx_comm.sim/rx_sim/behav/xsim/xsim.dir/SCI_RECEIVER_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html O:/ES31_22S/es31-worldle/vivado_projects/rx_tx_comm/rx_tx_comm.sim/rx_sim/behav/xsim/xsim.dir/SCI_RECEIVER_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm O:/ES31_22S/es31-worldle/vivado_projects/rx_tx_comm/rx_tx_comm.sim/rx_sim/behav/xsim/xsim.dir/SCI_RECEIVER_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
