# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: O:/ES31/es31-wordle/vivado_projects/master_project/master_project.srcs/sources_1/ip/wordle_dictionary_rom/wordle_dictionary_rom.xci
# IP: The module: 'wordle_dictionary_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ES31/es31-wordle/vivado_projects/master_project/master_project.srcs/sources_1/ip/wordle_dictionary_rom/wordle_dictionary_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_dictionary_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: O:/ES31/es31-wordle/vivado_projects/master_project/master_project.srcs/sources_1/ip/wordle_dictionary_rom/wordle_dictionary_rom.xci
# IP: The module: 'wordle_dictionary_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ES31/es31-wordle/vivado_projects/master_project/master_project.srcs/sources_1/ip/wordle_dictionary_rom/wordle_dictionary_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_dictionary_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
